### PR TITLE
Language data patch proposal.

### PR DESCRIPTION
**Pull request by Maikuolan**
#### Language data patch proposal.
*Priority: Low.*
*Backwards-Compatible: Yes.*

__Changes:__
- Re: "Locale Emulator is the name of the application, it is localized in some lang files but not in others. I think it is better to unify its translation." (proposed by @KagamiChan https://github.com/xupefei/Locale-Emulator/pull/204). This patch reverts the value of `<Submenu>Locale Emulator</Submenu>` in `LEContextMenuHandler/Lang/%%.xml` to the default value of the default language, for all language files.
- Re: "Should it be Exécuter?" (proposed by @KagamiChan https://github.com/xupefei/Locale-Emulator/pull/204). I'm not personally a native French speaker, but the "Exécuter" spelling is used by other instances of this word elsewhere in the language data, whereas the "Éxecuter" spelling is used only once. Additionally, Google search results favour the "Exécuter" spelling. I believe that "Exécuter" is more likely to be correct, whereas the "Éxecuter" spelling is *probably* a typographical error. This patch corrects "Éxecuter" to "Exécuter".
- Some language files terminated with linebreaks, whereas others didn't terminate with linebreaks. I'm unsure as to which of these (terminating with linebreaks versus *not* terminating with linebreaks) is preferred, but rules of majority suggest that *not* terminating with linebreaks is *probably* preferred (most files were like this). This patch unifies all language files to *not* terminating with linebreaks.
- Use of ellipses for the value of `<system:String x:Key="SaveAs">Save As ...</system:String>` in `LEGUI/Lang/%%.xaml` was not consistent (some language files used an ellipsis, whereas others didn't use an ellipsis). Additionally, whereas the majority of language files using an ellipsis, used an ellipsis in the form of three consecutive dots (...), and separated the ellipsis from the preceding text by a single space, not *all* language files did this. This patch unifies all language files to the use of an ellipsis in the form of three consecutive dots (...), separated from the preceding text by a single space.
- In the French language file "`LEGUI/Lang/fr.xaml`", there were three lines that separated language data from terminating grammatical marks with a space (respectively, a comma, an exclamation mark and a question mark). This patch removes those spaces.

### CODE REVIEW

**Comment by KagamiChan** [comment]
According to the [wiki](https://fr.wikipedia.org/wiki/Ponctuation#En_fran.C3.A7ais) , There's a space before colon, exclamation mark and question mark in France, but in other French-speaking countries the rule is not the same.

**Comment by Spidersouris** [comment]
Thanks for making that pull request :)
As a French native speaker, I'm gonna reply at some of your changes.
Yeah, it should be "Exécuter", I missed up with the accents, sorry!
Like @KagamiChan said, there should be a space before any colon or exclamation/question mark in French sentences. However, there's no need for any space before dots.
Thanks!

**Comment by Maikuolan** [comment]
> According to the wiki, there's a space before colon, exclamation mark and question mark in France, but in other French-speaking countries the rule is not the same. I suggest using the France style.

Huh.. So there is! Learn something new every day. Thanks for sharing this with me, and I agree; Better to use the France style (most native French speakers; makes the most sense). :+1: 

> Thanks for making that pull request :)
As a French native speaker, I'm gonna reply at some of your changes.
Yeah, it should be "Exécuter", I missed up with the accents, sorry!
As @KagamiChan said, there should be a space before any colon or exclamation/question mark in French sentences. However, there's no need for any space before dots.
Thanks!

No problem, and thanks for responding. :-)

Considering the above-mentioned, and also considering (in https://github.com/xupefei/Locale-Emulator/pull/203):

> Thanks for the explanation @regomne! So.. should I update the CREATE_SUSPENDED string translation?
Thanks @KagamiChan :smiley:

I think perhaps what I should do, is close this pull request, and send a new pull request, but without changing any of the French language files; It's possible that you'll need to send a new pull request for the French languages anyhow, to include the updated CREATE_SUSPENDED string (pending @regomne's response), so, if I ignore the French language files, maybe you could include the desirable changes from this pull request (while dropping the undesirable changes from this pull request) for the French language files in your next pull request? This way, too, the desirable changes from this pull request can be accepted without the risk of conflicting with possible imminent changes from other future pull requests.

Thoughts?

**Comment by regomne** [comment]
In xml, linebreaks are ignored, so we don't need to mind it.
For "Save as...", the meaning of the 3 dots is not an ellipsis. Generally, "..." is used when a menu item need an extra window to complete,(e.g. Open, Print, Replace, Go to in notepad), and on the other hand, a menu item without "..." means that it can complete without any other windows.(e.g. Save, Paste, and so on).

**Comment by mireado** [comment]
First of all,
Thanks for pull request.

btw., I have question about this.
**Why it need to unify its translation? 
I know 'Locale Emulator' is name, but is it reason for unifying?
Um... I think that is just matter of taste.


**I don't think 3 dots is a ellipsis.
And, If it is ellipsis, They need to be terminated cause it is useless on there lang(japanese, koreans etc).
That is kind of the translation.

Actually,
I think translation file is value on translation, not on the unifying.


Thank you for reading it.

**Comment by Maikuolan** [comment]
> In xml, linebreaks are ignored, so we don't need to mind it.

Cool cool. :+1: 

> First of all,
> Thanks for pull request.

No problem. I only discovered the Locale Emulator very recently (I needed the functionality that it provides for correctly running some foreign software that I recently adopted on my primary laptop), but I think it looks like a really cool program and I think it's a great idea, so, I was hoping to be able to help somewhere. :-)

> Um... I think that is just matter of taste.
This is true. Personally, I'm not so fond of translating program names, because I feel that it can cause ambiguity, and I feel that names should generally be the same regardless of language (wherever/whenever possible; sometimes, in some circumstances, unified names won't be possible), but, whether doing this is good or bad, could be argued either way, depending on perspective. Unifying the particular value in question, is included in this proposal, but, the proposal is simply a proposal and nothing more; Whether this part of the proposal or any other is accepted, I guess, is up to those managing this repository (so, with their say being the final say, I guess, it will depend on their tastes).

> I don't think 3 dots is a ellipsis.

Regarding this.. I think my meaning was slightly misunderstood. :-)
I'm working from __[this interpretation](https://en.wikipedia.org/wiki/Ellipsis#Computer_interfaces)__ of the ellipsis:
> In many user interface guidelines, a "…" after the name of a command implies that the user will need to provide further information, for example in a subsequent dialog box, before the action can be completed. A typical example is the Save As… command, which after being clicked will usually require the user to enter a filename, as opposed to Save where the file will usually be saved under its existing name.
>
> An ellipsis character after a status message signifies that an operation is in progress and may take some time, as in "Downloading updates…".

Anyway, that doesn't matter so much; Whether it's an ellipsis or something else, if it doesn't make sense for other languages, then, we shouldn't need it, so we won't need this change.

If we don't need that change, if we're not worrying about linebreaks, if we're not unifying the program name across languages, and also, if native French includes the space normally (and so, this part of the proposal should be rejected anyway), then, we can close this pull request now.

Let me know if I should send a new pull request with an adjusted proposal. :+1:

**Comment by KagamiChan** [comment]
> Why it need to unify its translation?
> I know 'Locale Emulator' is name, but is it reason for unifying?
> Um... I think that is just matter of taste.

The situation is that the app name translation is not consistent, in some language files the application name is localized but in others not. This may confuse users who switch to a new language. We have 3 choices here:

1. Unify the name, don't translate it;
2. make it localized as per language;
3. leave it to translators' preference.

I recommend the 1st choice because it is good for branding, and many other softwares do the same.

**Comment by Spidersouris** [comment]
Yeah, the 1st choice is better imo.

**Pull request closed without merging**
