### PR TITLE
Added Lithuanian locale

### PR DESCRIPTION
**Pull request by rimas-kudelis**
This adds Lithuanian locale. I prefer it to be called just 'lt' as opposed to 'lt-LT', but I guess there are some technical limitations which make this undesired, or am I wrong?

### CODE REVIEW

**Comment by xupefei** [comment]
Thank you.
I am not sure the code for your language, so would you please run this small app and see what's the output?
http://www.filedropper.com/uilangtest

**Comment by rimas-kudelis** [comment]
The output is lt-LT, just as expected. However, at least to my understanding, the OS should specify as detailed locale info as possible (language and country codes in this case), whereas the application localizers should aim at making their locale as broad as reasonable instead of as narrow as possible. For example, if there are no differences between localizations for language A in country X and language A in country Y, then there is no reason to specify A-X or A-Y as their target locale, just A should be enough. I don't know if Windows supports that view though.

**Comment by xupefei** [comment]
I understand your opinion, but things are not always same. For example in your language `lt` is the same as `lt-LT`, but in my mother tongue, Chinese, there are Simplified (`zh-CN`), Hongkong Traditional (zh-HK) and Taiwan Traditional (zh-TW) version. They are quite different in writing, pronunciation as well as the grammar. So in this case only `zh` is not enough.

Another idea may be `fallback`: e.g. First try to find language file `lt-LT`, if not, fallback to `lt` instead. But as this is rarely needed, I doubt if it is really need.

Is there many variants in Lithuanian language?

**Comment by rimas-kudelis** [comment]
Yeah, I know about the situation with Chinese. Chinese is one of the few cases where just "zh" doesn't make sense. But for a lot of other languages it does. Take English for example: the list of English locales in your application is huge, but it would hardly make any sense to duplicate translations (if there were any) for each one of them. Or look at German: there are six to seven German locales in the list, but it's safe to assume that the translations for all of them would be the same.

Then again, correct locale names for Chinese would include writing system in them as well (Hans vs. Hant). And if China is the only country using Simplified Chinese writing system, then having CN in the code might be unnecessary. ;)

Regarding fallback scenario: this is exactly how things should work. And I don't even think you should be implementing this fallback yourself, since it should be implemented in the tookit/framework that you use. Unless of course it is not implemented there in which case it's understandable why so many Windows applications use long locale codes instead of short ones.

Regarding Lithuanian in particular, there is only one variant of it, so at least to me, this discussion is more theoretical than practical. Both `lt` and `lt-LT` will work the same, I suppose.

**Comment by xupefei** [comment]
Please rename your translation file :)

**Comment by rimas-kudelis** [comment]
Done. Please also check out my comment on your commit. ;)

**Pull request merged**
